### ISSUE TITLE
Null reference fails to decompile

### ISSUE THREAD

**Issue by GraxCode** [leibnitz27/cfr#147]
Compiling and decompiling this simple code leads to a NPE. (version 0.149)
```java
public enum CrashEnum {
	SAMPLE;

	public CrashEnum[] cloneValues() {
		return ((CrashEnum[]) null).clone();
	}
}
```
[CrashEnum.class.txt](https://github.com/leibnitz27/cfr/files/4533778/CrashEnum.class.txt)

**Comment by leibnitz27** [comment]
What environment are you testing this under?  The class file you gave doesn't NPE under anything I throw at it.

```
C:\Users\Lee\code\cfr\target\classes>"c:\Program Files\Java\jdk1.6.0_45\bin\java.exe" -jar c:\Users\Lee\website\other\cfr\cfr-0.149.jar c:\Downloads\CrashEnum.class
/*
 * Decompiled with CFR 0.149.
 */
package testing;

public enum CrashEnum {
    SAMPLE;


    public CrashEnum[] cloneValues() {
        return (CrashEnum[])((Enum)null).clone();
    }
}

C:\Users\Lee\code\cfr\target\classes>"c:\Program Files\Java\jdk-14\bin\java.exe"  -jar c:\Users\Lee\website\other\cfr\cfr-0.149.jar c:\Downloads\CrashEnum.class
/*
 * Decompiled with CFR 0.149.
 */
package testing;

public enum CrashEnum {
    SAMPLE;


    public CrashEnum[] cloneValues() {
        return (CrashEnum[])((Enum)null).clone();
    }
}
```

**Comment by GraxCode** [comment]
I built cfr-0.150 and it seems to decompile properly now. In 0.149 it threw a `java.lang.NullPointerException at org.benf.cfr.reader.bytecode.analysis.types.discovery.InferredJavaType$IJTInternal_Impl.getRawType(InferredJavaType.java:475)
`
Was probably fixed by fixing something else. My mistake.

**Comment by GraxCode** [comment]
I mean, either way the code is invalid, as `((CrashEnum[]) null).clone()` would be correct. `(CrashEnum[])((Enum)null).clone()` is incorrect because `Enum` has no visible `clone` method. It won't compile.

**Comment by leibnitz27** [comment]
I'm still intrigued re the NPE - I didn't fix anything there, and you said it breaks in stock 0.149

**Comment by GraxCode** [comment]
I noticed it doesn't occur via command line. The problem is likely my API usage, and not fixed in 0.150.
```java
	private static String decompiled;

	public static String decompile(ClassNode cn) {
		try {
			byte[] bytes = Conversion.toBytecode0(cn);
			decompiled = null;
			OutputSinkFactory mySink = new OutputSinkFactory() {
				@Override
				public List<SinkClass> getSupportedSinks(SinkType sinkType, Collection<SinkClass> collection) {
					if (sinkType == SinkType.JAVA && collection.contains(SinkClass.DECOMPILED)) {
						return Arrays.asList(SinkClass.DECOMPILED, SinkClass.STRING);
					} else {
						return Collections.singletonList(SinkClass.STRING);
					}
				}
				@Override
				public <T> Sink<T> getSink(SinkType sinkType, SinkClass sinkClass) {
					if (sinkType == SinkType.JAVA && sinkClass == SinkClass.DECOMPILED) {
						return x -> { decompiled = ((SinkReturns.Decompiled)x).getJava(); };
					}
					return ignore -> {};
				}
			};
			ClassFileSource source = new ClassFileSource() {
				@Override
				public void informAnalysisRelativePathDetail(String a, String b) {
				}

				@Override
				public String getPossiblyRenamedPath(String path) {
					return path;
				}

				@Override
				public Pair<byte[], String> getClassFileContent(String path) throws IOException {
					String name = path.substring(0, path.length() - 6);
					if (name.equals(cn.name)) {
						return Pair.make(bytes, name);
					}
					ClassNode dummy = new ClassNode();
					dummy.name = name;
					dummy.version = 52;
					return Pair.make(Conversion.toBytecode0(dummy), name); // cfr loads unnecessary classes
				}

				@Override
				public Collection<String> addJar(String arg0) {
					throw new RuntimeException();
				}
			};
			CfrDriver cfrDriver = new CfrDriver.Builder().withClassFileSource(source).withOutputSink(mySink).withOptions(options).build();
			cfrDriver.analyse(Arrays.asList(cn.name));
		} catch (Exception e) {
			e.printStackTrace();
			StringWriter sw = new StringWriter();
			PrintWriter pw = new PrintWriter(sw);
			e.printStackTrace(pw);
			return sw.toString();
		}
		return decompiled;
	}
```
The problem source is probably `getClassFileContent`, because i do only load the class i want to decompile. CFR in Bytecode Viewer 2.9.22 fails too, because it probably uses the API similarly. Here is the full stack trace: 
```     
// java.lang.NullPointerException
        // org.benf.cfr.reader.bytecode.analysis.types.discovery.InferredJavaType$IJTInternal_Impl.getRawType(InferredJavaType.java:475)
        // org.benf.cfr.reader.bytecode.analysis.types.discovery.InferredJavaType.getRawType(InferredJavaType.java:1174)
        // org.benf.cfr.reader.bytecode.analysis.parse.expression.CastExpression.<init>(CastExpression.java:29)
        // org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.transformers.NakedNullCaster.rewriteExpression(NakedNullCaster.java:44)
        // org.benf.cfr.reader.bytecode.analysis.parse.expression.CastExpression.applyExpressionRewriter(CastExpression.java:109)
        // org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.transformers.NakedNullCaster.rewriteExpression(NakedNullCaster.java:49)
        // org.benf.cfr.reader.bytecode.analysis.structured.statement.StructuredReturn.rewriteExpressions(StructuredReturn.java:90)
        // org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.transformers.NakedNullCaster.transform(NakedNullCaster.java:31)
        // org.benf.cfr.reader.bytecode.analysis.opgraph.Op04StructuredStatement.transform(Op04StructuredStatement.java:675)
        // org.benf.cfr.reader.bytecode.analysis.structured.statement.Block.transformStructuredChildren(Block.java:423)
        // org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.transformers.NakedNullCaster.transform(NakedNullCaster.java:30)
        // org.benf.cfr.reader.bytecode.analysis.opgraph.Op04StructuredStatement.transform(Op04StructuredStatement.java:675)
        // org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.transformers.NakedNullCaster.transform(NakedNullCaster.java:25)
        // org.benf.cfr.reader.bytecode.analysis.opgraph.Op04StructuredStatement.miscKeyholeTransforms(Op04StructuredStatement.java:760)
        // org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisInner(CodeAnalyser.java:784)
        // org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisOrWrapFail(CodeAnalyser.java:184)
        // org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysis(CodeAnalyser.java:129)
        // org.benf.cfr.reader.entities.attributes.AttributeCode.analyse(AttributeCode.java:96)
        // org.benf.cfr.reader.entities.Method.analyse(Method.java:397)
        // org.benf.cfr.reader.entities.ClassFile.analyseMid(ClassFile.java:906)
        // org.benf.cfr.reader.entities.ClassFile.analyseTop(ClassFile.java:797)
        // org.benf.cfr.reader.Driver.doClass(Driver.java:58)
```

**Comment by GraxCode** [comment]
I changed it to 
```java
			@Override
				public Pair<byte[], String> getClassFileContent(String path) throws IOException {
					String name = path.substring(0, path.length() - 6);
					if (name.equals(cn.name)) {
						return Pair.make(bytes, name);
					}
					if (path.replace('/', '.').matches(VM.RT)) {
						return Pair.make(IOUtils.toByteArray(CFR.class.getResource(path)), name);
					}
					ClassNode dummy = new ClassNode();
					dummy.name = name;
					dummy.version = 52;
					return Pair.make(Conversion.toBytecode0(dummy), name); // cfr loads unnecessary classes
				}
```
so runtime classes get loaded too, but this does not fix the problem. The problem seems to originate somewhere else.

**Comment by leibnitz27** [comment]
> Why is getClassFileContent needed?

  You're specifying that you have a better way to resolve a class's path to bytecode than the default.

All classes have dependencies - at *least* java.lang.Object.    (and probably way more - printstream etc).   CFR doesn't make *any* assumptions about how these behave - it loads them and tries to match up (to generate overrides annotations, infer generic call info etc).

In this case, usage definitely seems suspect - whatever the bytecode that getByteCode0 returns - (what is that?) is not going to resemble the implicit contract.

It's definitely worth fixing whatever is causing CFR to blow here, but you should probably avoid feeding it deliberately bad data - just throw a FileNotFound exception, like in the example client.

Can you provide the output of Conversion.toBytecode0(dummy)?

**Comment by GraxCode** [comment]
`Conversion.toBytecode0(dummy)` produces an empty class file in bytes. But it doesn't matter, as it is not the cause of the problem. Here's how to reproduce the NPE:
```java
	public static void main(String... args) {
		CfrDriver driver = new CfrDriver.Builder().withClassFileSource(new DataSource()).build();
		driver.analyse(Arrays.asList("CrashEnum.class"));
	}

	public static class DataSource implements ClassFileSource {
		@Override
		public void informAnalysisRelativePathDetail(String usePath, String classFilePath) {
		}

		@Override
		public Collection<String> addJar(String jarPath) {
			throw new UnsupportedOperationException();
		}

		@Override
		public String getPossiblyRenamedPath(String path) {
			return path;
		}

		@Override
		public Pair<byte[], String> getClassFileContent(String path) throws IOException {
			if (!path.equals("CrashEnum.class"))
				throw new FileNotFoundException("Can't find " + path);
			return Pair.make(Files.readAllBytes(new File("CrashEnum.class").toPath()), "CrashEnum.class");
		}
	}
```
Don't forget to place the class file in the same directory!

**Comment by GraxCode** [comment]
I now remember why i used a dummy class instead of just throwing an FNF exception. CFR creates very long comments at the top of the decompiled class file like 
``` 
Could not load the following classes: 
XXX
YYY
ZZZ
```
They are pretty annoying on long class files, and I'm not sure if there is a way to disable them.
